#include "memtypes.h"

const char *mtype_str[] = 
{
	"MTYPE_LIST",
	"MTYPE_LIST_NODE",
	"MTYPE_HASH",
	"MTYPE_HASH_INDEX",
	"MTYPE_HASH_BACKET",
	"MTYPE_EVENT_NODE",
	"MTYPE_EVENT_MASTER",
	"MTYPE_EPOLL_EVENT",
	"MTYPE_PEER",
	"MTYPE_TCP_CLIENT_INFO_NODE",
	"MTYPE_TCP_SERVER_INFO_NODE",
	"MTYPE_STREAM_FIFO",
	"MTYPE_STREAM",
	"MTYPE_STREAM_DATA",
	"MTYPE_STRING",
	"NULL"
};
